############################
# Pre-commit configuration #
############################

# Install via `pip install pre-commit`

# This is run as a precondition to commits, run manually via `pre-commit run`

# When adding new hooks, it may make sense to once run
# `pre-commit run --all-files` as by default only changed files are checked

# Automatically run before every commit via once running `pre-commit install`

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
#- repo: https://github.com/nbQA-dev/nbQA
#  rev: 1.6.3
#  hooks:
#    # Run ruff for jupyter notebooks.
#    - id: nbqa-ruff
#      args: [--ignore=E402]  # E402: module level import not at top of file
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  # A bunch of other pre-defined hooks.
  - id: check-yaml
    description: Check yaml files for parseable syntax
  - id: check-added-large-files
    description: Prevent large files from being committed
  - id: check-merge-conflict
    description: Check for files that contain merge conflict strings
  - id: check-symlinks
    description: Check for symlinks which do not point to anything
  - id: trailing-whitespace
    description: Trim trailing whitespaces
  - id: end-of-file-fixer
    description: Fix empty lines at ends of files
  - id: detect-private-key
    description: Detects the presence of private keys
